//! Build-time helper: read the previously-built kernel binary and
//! emit a Rust source file with a sorted (address, size, name) symbol
//! table.  The kernel's `crate::symbols` module includes this file via
//! `include!(concat!(env!("OUT_DIR"), "/symbols.rs"))`.
//!
//! ## Two-pass model
//!
//! `build.rs` runs before the kernel itself is compiled, so the very
//! first build produces an empty table.  After that build emits the
//! ELF, the *next* `cargo build` reads it and embeds the symbols of
//! that previous binary.  Symbol addresses for stable code drift only
//! by a few hundred bytes between near-identical builds, so a panic
//! backtrace looking up a RIP against the prior table picks the right
//! function 99% of the time — exactly the same trick the Linux
//! kernel's `kallsyms` two-stage build uses.

use std::env;
use std::fs;
use std::io::Write;
use std::path::Path;
use std::process::Command;

fn main() {
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set");
    let dest = Path::new(&out_dir).join("symbols.rs");

    // Allow custom location via env, default to release target dir.
    let kernel_path = env::var("RUSTOS_KERNEL_BINARY")
        .unwrap_or_else(|_| "target/x86_64-rustos/release/rustos".to_string());

    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed={}", kernel_path);
    println!("cargo:rerun-if-env-changed=RUSTOS_KERNEL_BINARY");

    let mut symbols: Vec<(u64, u64, String)> = Vec::new();
    if Path::new(&kernel_path).exists() {
        let nm = Command::new("nm")
            .args(&["--defined-only", "--print-size", &kernel_path])
            .output();
        if let Ok(out) = nm {
            for line in String::from_utf8_lossy(&out.stdout).lines() {
                // Format: "addr size type name" — name may be missing
                // for non-function symbols; size is sometimes blank.
                let mut it = line.split_whitespace();
                let addr_s = match it.next() { Some(s) => s, None => continue };
                let size_s = match it.next() { Some(s) => s, None => continue };
                let typ_s = match it.next() { Some(s) => s, None => continue };
                let name = match it.next() { Some(s) => s, None => continue };
                // Only accept text symbols ('T' = global, 't' = local).
                if !(typ_s == "T" || typ_s == "t") { continue; }
                let addr = match u64::from_str_radix(addr_s, 16) { Ok(v) => v, Err(_) => continue };
                let size = u64::from_str_radix(size_s, 16).unwrap_or(0);
                if addr == 0 { continue; }
                symbols.push((addr, size, name.to_string()));
            }
        }
    }

    symbols.sort_by_key(|t| t.0);
    symbols.dedup_by_key(|t| t.0);

    let mut f = fs::File::create(&dest).expect("create symbols.rs");
    writeln!(f, "// AUTO-GENERATED by build.rs — do not edit").unwrap();
    writeln!(f, "// Source: {}", kernel_path).unwrap();
    writeln!(f, "pub static SYMBOLS: &[(u64, u64, &str)] = &[").unwrap();
    for (addr, size, name) in &symbols {
        // Escape backslashes and double-quotes; Rust symbol names from
        // the mangler are otherwise plain ASCII.
        let escaped = name.replace('\\', "\\\\").replace('"', "\\\"");
        writeln!(f, "    ({:#x}, {:#x}, \"{}\"),", addr, size, escaped).unwrap();
    }
    writeln!(f, "];").unwrap();
    println!("cargo:warning=symbols.rs: embedded {} symbols", symbols.len());
}
