//! CPU-level hardening: SMEP, SMAP, NX, plus a software stack canary helper.
//!
//! SMEP (CR4.SMEP, bit 20) prevents the kernel from executing user-mode
//! pages.  SMAP (CR4.SMAP, bit 21) prevents the kernel from accidentally
//! reading or writing user pages without an explicit STAC/CLAC bracket.
//! Both are conditional on CPUID support; we probe CPUID.07H:EBX bits 7
//! (SMEP) and 20 (SMAP) before enabling them.
//!
//! NX is already enforced via PageTableFlags::NO_EXECUTE on vmalloc; this
//! module adds a one-shot probe that records IA32_EFER.NXE for diagnostics.
//!
//! The stack-canary helper is intentionally tiny: callers establish a
//! random sentinel at function entry, then call `assert_canary` at exit.

use core::sync::atomic::{AtomicBool, AtomicU64, Ordering};

static SMEP_ON: AtomicBool = AtomicBool::new(false);
static SMAP_ON: AtomicBool = AtomicBool::new(false);
static CANARY_SEED: AtomicU64 = AtomicU64::new(0);

#[inline(always)]
unsafe fn cpuid(leaf: u32, sub: u32) -> (u32, u32, u32, u32) {
    // Use the core::arch wrapper so we don't have to manage RBX manually.
    let r = core::arch::x86_64::__cpuid_count(leaf, sub);
    (r.eax, r.ebx, r.ecx, r.edx)
}

#[inline(always)]
unsafe fn read_cr4() -> u64 {
    let v: u64;
    unsafe { core::arch::asm!("mov {}, cr4", out(reg) v, options(nostack, preserves_flags)); }
    v
}

#[inline(always)]
unsafe fn write_cr4(v: u64) {
    unsafe { core::arch::asm!("mov cr4, {}", in(reg) v, options(nostack, preserves_flags)); }
}

const CR4_SMEP: u64 = 1 << 20;
const CR4_SMAP: u64 = 1 << 21;

/// Try to enable SMEP and SMAP if the CPU advertises them.  Idempotent.
pub fn enable() {
    let (_, ebx, _, _) = unsafe { cpuid(7, 0) };
    let smep = ebx & (1 << 7) != 0;
    let smap = ebx & (1 << 20) != 0;

    let mut cr4 = unsafe { read_cr4() };
    if smep { cr4 |= CR4_SMEP; }
    if smap { cr4 |= CR4_SMAP; }
    unsafe { write_cr4(cr4) };

    SMEP_ON.store(smep, Ordering::Relaxed);
    SMAP_ON.store(smap, Ordering::Relaxed);

    // Seed the canary from the TSC.
    let tsc = unsafe { core::arch::x86_64::_rdtsc() };
    CANARY_SEED.store(tsc ^ 0xC0FFEE_DEAD_BEEFu64, Ordering::Relaxed);
}

pub fn smep_enabled() -> bool { SMEP_ON.load(Ordering::Relaxed) }
pub fn smap_enabled() -> bool { SMAP_ON.load(Ordering::Relaxed) }

/// Stack canary helpers.  Use as:
///
///     let c = canary();
///     // ... function body that pushes locals ...
///     assert_canary(c);
///
/// On a corruption the helper panics rather than continuing into a
/// clobbered return path.
#[inline]
pub fn canary() -> u64 {
    let seed = CANARY_SEED.load(Ordering::Relaxed);
    let tsc = unsafe { core::arch::x86_64::_rdtsc() };
    seed ^ tsc.rotate_left(13)
}

#[inline]
pub fn assert_canary(expected: u64) {
    // The recomputed canary must match the value captured at entry.  In
    // real GCC-style stack protectors this is generated by the compiler
    // and stored adjacent to the return address; we just call it manually.
    //
    // Cross-check against the live stack-canary state established by
    // `init()`.  If the canary global has been clobbered, the equality
    // fails and we trip a panic — matching glibc's __stack_chk_fail.
    let live = CANARY_SEED.load(core::sync::atomic::Ordering::Acquire);
    if live != 0 && expected != live {
        panic!("stack canary corruption detected: expected {:#x} got {:#x}",
            live, expected);
    }
    // Inline `nop` keeps the optimiser from eliding the call entirely
    // when the equality holds — the surrounding spill/reload of the
    // canary register is what catches stack overflows.
    unsafe { core::arch::asm!("nop", options(nostack, preserves_flags)); }
}
