//! Symbolisation for kernel panics: maps a runtime instruction pointer
//! back to the function that contains it.
//!
//! The symbol table itself is generated by `build.rs` from the
//! previously-built kernel binary (see that file's docstring for the
//! two-pass build model).  This module exposes a single function,
//! `lookup`, which performs a binary search on that sorted
//! (addr, size, name) list and returns the symbol's name plus the
//! offset within it.
//!
//! Demangling: Rust's modern v0 mangling is verbose
//! ("_RINvMNtCs..."); we strip the trailing hash suffix to make
//! traces readable but leave the rest as-is.  A full v0 demangler is
//! out of scope here.

include!(concat!(env!("OUT_DIR"), "/symbols.rs"));

/// Look up `addr`.  Returns the matching symbol's name, the offset
/// of `addr` from the symbol's start, and an optional source-file:line
/// (empty string when the build had no DWARF or addr2line couldn't
/// resolve the symbol's start).
pub fn lookup(addr: u64) -> Option<(&'static str, u64, &'static str)> {
    if SYMBOLS.is_empty() { return None; }
    let idx = match SYMBOLS.binary_search_by_key(&addr, |t| t.0) {
        Ok(i)  => i,
        Err(0) => return None,
        Err(i) => i - 1,
    };
    let (start, size, name, loc) = SYMBOLS[idx];
    let offset = addr - start;
    if size != 0 && offset >= size { return None; }
    Some((name, offset, loc))
}

/// Try to extract the most readable substring from a Rust-mangled
/// symbol.  The full v0 grammar (rustc RFC 2603) is intricate; the
/// trick we use here exploits the fact that v0 names always end with
/// the actual function name in `<decimal-len><identifier>` form, so
/// we walk *backwards* from the end of the string until we find the
/// longest trailing identifier whose length is preceded by exactly
/// the matching decimal run.  Falls back to the full (un-`_R`-prefix)
/// mangled name when no such suffix is found — better than nothing.
pub fn pretty_name(mangled: &str) -> &str {
    let s = mangled.strip_prefix("_R").unwrap_or(mangled);
    let s = s.strip_prefix("_ZN").unwrap_or(s);
    let bytes = s.as_bytes();
    if bytes.is_empty() { return s; }

    // Find the longest trailing run of identifier bytes (alnum / _).
    let mut name_end = bytes.len();
    let mut name_start = name_end;
    while name_start > 0
        && (bytes[name_start - 1].is_ascii_alphanumeric() || bytes[name_start - 1] == b'_')
    {
        name_start -= 1;
    }
    if name_start == name_end { return s; }

    // Trim leading digits off the identifier — those are the v0
    // length prefix.  Keep shrinking the name from the front until the
    // preceding run of digits parses to exactly the remaining length.
    let mut start = name_start;
    while start < name_end {
        // Walk back over the digits immediately before `start`.
        let mut d_end = start;
        let mut d_start = start;
        while d_start > 0 && bytes[d_start - 1].is_ascii_digit() {
            d_start -= 1;
        }
        if d_start == d_end {
            // No length prefix here; advance start by one and try again.
            start += 1;
            continue;
        }
        let mut n: usize = 0;
        for &b in &bytes[d_start..d_end] {
            n = n * 10 + (b - b'0') as usize;
        }
        if n == name_end - start && n > 0 && n <= 64 {
            // Match.  bytes[start..name_end] is the function name.
            return core::str::from_utf8(&bytes[start..name_end]).unwrap_or(s);
        }
        start += 1;
    }
    s
}

/// How many symbols were embedded by the build.  0 on the very first
/// build; populated on the second.
pub fn count() -> usize { SYMBOLS.len() }
